### ISSUE TITLE
 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by rfiedler** [rodhoward/node-sybase#10]
Hi , 
Sybase Version  :  11.92  jTDS Type 4 JDBC Driver  (Using DBVisualizer) 
My NODEJS Version:  0.10.25

```
fiedler@huhomolog:/home/node/api$ nodejs server.js
NodeJs Started... listen

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

This error raise while excute db.connect. (same parameters for DBVisualizer Works ! )

**DBVisualizer Works with connection parameters**
![dbvisualizer works with conecction parameters](https://cloud.githubusercontent.com/assets/1020057/24101876/b374ca96-0d58-11e7-98db-8add1854f6cb.jpg)

**NODE ERROR**
![nodejs console error](https://cloud.githubusercontent.com/assets/1020057/24101878/b38779c0-0d58-11e7-975c-4c4c0ed75a4b.jpg)

**MY CODE**
![node code](https://cloud.githubusercontent.com/assets/1020057/24101877/b374e03a-0d58-11e7-8b54-1000790c7ac2.jpg)

What Happen's ?  I need Help !

Tks !

**Comment by rfiedler** [comment]
Solved ! 

In Linux enviroment , JAVA_HOME required to application work !

**Comment by arjunrao87** [comment]
Your solution gave me the hint I was looking for! Did not have java installed in my container. Wayyy too many hours spent on this :-)
