### ISSUE TITLE
Does this library need to support Node < 6?

### ISSUE THREAD

**Issue by theneva** [rodhoward/node-sybase#20]
Node 6 has [been in LTS since October last year](https://github.com/nodejs/Release), and Node 8 is [scheduled to enter LTS in October](https://nodejs.org/en/blog/release/v8.0.0/).

This library makes heavy use of things like `function` which requires things like `var this = that;` (compare with arrow functions), and `var` which has been replaced with `const` and `let`.

I'd be happy to send a PR with what an "upgrade" to Node 6 would look like if upgrading is a possibility.

**Comment by rodhoward** [comment]
yeah its like going back in a time machine! I think we leave it as is because the test cases aren't great and we can't test it ourselves.
