### ISSUE TITLE
remove console logs from query method!

### ISSUE THREAD

**Issue by igniteram** [rodhoward/node-sybase#23]
I will send in a PR when I get time, meanwhile tracking this issue!

**Comment by mattsmith2017** [comment]
any update on this?

**Comment by igniteram** [comment]
@mattsmith2017 A PR is already open for this issue - https://github.com/rodhoward/node-sybase/pull/22

**Comment by rodhoward** [comment]
Yeah sorry but as I don't have access to Sybase any more, I'm not actively
updating this library.

**Comment by iocapps** [comment]
Well, now what?

**Comment by theneva** [comment]
@iocapps now nothing, I guess. I don't have access to a Sybase instance anymore either, so I can't really help out.

I'm sure mr. Howard would be happy to give maintainer status to someone with access and interest in its continued development. Would you be interested?

**Comment by tamaker** [comment]
@iocapps I have access to sybase, am actively using this project (in production) and am interested in knowing what I need to do to be considered for taking over as maintainer on this project.  Thanks!

**Comment by theneva** [comment]
This is definitely a question for @rodhoward :smile:

**Comment by rodhoward** [comment]
So ten years later I think this is resolved now..
