### ISSUE TITLE
Version 1.2.2 throws an "encoding is not defined" error.

### ISSUE THREAD

**Issue by gustavocipriani** [rodhoward/node-sybase#31]
This is how I am instancing Sybase (works for 1.2.1):
let db = new this.Sybase(this.host, this.port, this.dbName, this.username, this.pw, true, this.javaJarPath);

But in 1.2.2, I'm getting this error.

D:\workspace\mysybaseproject\dist\node_modules\sybase\src\SybaseDB.js:55
                that.javaDB.stdout.setEncoding(encoding).pipe(that.jsonParser).on("data", function(jsonMsg) { that.onSQLResponse.call(that, jsonMsg); });
                                               ^
ReferenceError: encoding is not defined
    at Socket.<anonymous> (D:\workspace\mysybaseproject\dist\node_modules\sybase\src\SybaseDB.js:55:34)

Thanks!

**Comment by rodhoward** [comment]
Thanks sorry about that Ill take a look today

**Comment by rodhoward** [comment]
Should be fixed.
