### ISSUE TITLE
[Discussion] on condition which leaves out the column from response if it's value was null

### ISSUE THREAD

**Issue by Vimal-N** [rodhoward/node-sybase#32]
https://github.com/rodhoward/node-sybase/blob/407f47d014660a759cfb213ed2e91010ec11ccb4/JavaSybaseLink/src/ExecSQLCallable.java#L72

Hi @rodhoward , was there any particular reason which made you to leave out the column from being returned back on the response set if it's value was `null`? or was it the choice to keep the response structure light weight as possible?

**Comment by rodhoward** [comment]
Yeah null and undefined are one and the same in JavaScript I prefer to just keep everything undefined and never deal with null. Plus it's a little lighter.
